"""timeit -> PerfMeasurement, through the sandbox.

The Profiler is the critic most able to invent numbers, so this module is built so that it
cannot. Three constraints do that work:

1. **The runner template is ours.** Only a benchmark *expression* comes from the model, it is
   embedded as a JSON string literal, and `astgate.assert_single_call_expression` has already
   proved it is one call and not a statement list. `parse_records(rows)` is accepted;
   `parse_records(rows); import os; os.system("...")` does not parse as an expression at all.
2. **Setup is expressions only.** Setup arrives as `name -> expression` pairs, each validated
   with `ast.parse(mode="eval")`. There is no way to smuggle an import or a statement through
   a field that only accepts expressions.
3. **`unmeasurable` and `inconclusive` are first-class.** Most snippets have no runnable
   benchmark, and two timings inside each other's noise are not evidence of anything.
   `PerfMeasurement.is_citable` is False for both, and the Profiler is required to honour it
   (docs/09-roadmap.md Phase 2 acceptance criteria).
"""

from __future__ import annotations

import ast
import json
import statistics
from dataclasses import dataclass, field
from pathlib import Path

from tribunal.astgate import assert_single_call_expression
from tribunal.contracts import PerfMeasurement
from tribunal.sandbox import ExecutionNotPermitted, Sandbox, scratch_dir

TOOL = "perf"
RUNNER_NAME = "_bench_runner.py"

#: A difference smaller than both of these is reported as `inconclusive`. Two gates because
#: either alone is wrong: a pure relative gate calls a 4% move on a noisy measurement real,
#: and a pure noise gate calls a 1% move on a very stable measurement real.
MIN_RELATIVE_DELTA = 0.05
NOISE_SIGMAS = 2.0

#: docs/03-agents.md § 3.3: "If `stdev_ns > 0.15 x mean`, the measurement is `inconclusive`
#: and MUST NOT be cited as a MEASUREMENT evidence."
#:
#: This is a gate on the *measurement's own quality*, independent of how big the difference
#: is. A 40% regression measured on a machine whose timings vary by 30% is not evidence of a
#: regression -- it is evidence of a loaded machine. Without this rule a large delta on a
#: noisy run would be reported as `slower`, which is exactly where a performance critic
#: starts inventing percentages.
MAX_NOISE_RATIO = 0.15

#: Same section: "Minimum 5 repeats; report `stdev`." A single timing has no spread to report,
#: so it cannot be shown to be outside the noise.
MIN_REPEATS = 5

RUNNER_TEMPLATE = '''\
"""Generated by tribunal. Do not edit; regenerated per measurement."""
import json
import statistics
import sys
import timeit

SPEC = json.loads(sys.argv[1])

module = __import__(SPEC["module"])
env = dict(vars(module))
for name, expression in SPEC["setup"].items():
    env[name] = eval(expression, env)  # noqa: S307 - expression validated by astgate

timer = timeit.Timer(SPEC["expression"], globals=env)
try:
    number, _ = timer.autorange()
    raw = timer.repeat(repeat=SPEC["repeats"], number=number)
except Exception as exc:
    print(json.dumps({"error": f"{type(exc).__name__}: {exc}"}))
    raise SystemExit(0)

per_call = [(t / number) * 1e9 for t in raw]
print(json.dumps({
    "number": number,
    "repeats": len(per_call),
    # Best-of, not mean: timeit's own guidance. The minimum is the least contaminated by
    # scheduling noise, and we want the code's cost, not the machine's mood.
    "best_ns": int(min(per_call)),
    "stdev_ns": int(statistics.stdev(per_call)) if len(per_call) > 1 else 0,
}))
'''


@dataclass(frozen=True)
class Benchmark:
    """A declared entry point to measure. `label` becomes the `PerfMeasurement.label`."""

    label: str
    expression: str
    setup: dict[str, str] = field(default_factory=dict)
    repeats: int = 9

    def validate(self) -> None:
        assert_single_call_expression(self.expression)
        for name, expression in self.setup.items():
            if not name.isidentifier():
                raise ValueError(f"setup name {name!r} is not an identifier")
            try:
                ast.parse(expression, mode="eval")
            except SyntaxError as exc:
                raise ValueError(
                    f"setup {name!r} must be a single expression: {exc.msg}"
                ) from exc


def unmeasurable(label: str, reason: str) -> PerfMeasurement:
    """The honest answer when there is nothing to measure.

    Returned rather than raised, because "no benchmark exists" is the common case and the
    design absorbs it without special-casing: the schema already carries the verdict.
    """
    return PerfMeasurement(
        label=f"{label} ({reason})",
        before_ns=None,
        after_ns=None,
        repeats=0,
        stdev_ns=None,
        verdict="unmeasurable",
    )


@dataclass(frozen=True)
class PerfTool:
    sandbox: Sandbox

    def time_once(
        self, source: str, benchmark: Benchmark, logical_name: str = "target.py"
    ) -> tuple[int, int] | str:
        """Time one source. Returns `(best_ns, stdev_ns)` or an error string.

        `logical_name` is the file's real basename, not a fixed "target.py": the benchmark
        expression names functions from the module under test, and staging it under a
        different name would make every measurement an ImportError.
        """
        try:
            benchmark.validate()
        except ValueError as exc:
            return str(exc)
        spec = {
            "module": Path(logical_name).stem,
            "expression": benchmark.expression,
            "setup": benchmark.setup,
            "repeats": benchmark.repeats,
        }
        with scratch_dir({logical_name: source, RUNNER_NAME: RUNNER_TEMPLATE}) as workdir:
            try:
                result = self.sandbox.run(
                    [
                        self.sandbox.python_for_sandbox(),
                        RUNNER_NAME,
                        json.dumps(spec, sort_keys=True),
                    ],
                    workdir,
                    source_to_gate=source,
                )
            except ExecutionNotPermitted as exc:
                return str(exc)
        if result.refused_reason is not None:
            return result.refused_reason
        if result.timed_out:
            return f"benchmark timed out after {result.duration_ms}ms"
        if not result.ok:
            tail = (result.stderr or result.stdout).strip().splitlines()[-3:]
            return f"benchmark exited {result.exit_code}: {' / '.join(tail)[:300]}"
        try:
            payload = json.loads(result.stdout.strip().splitlines()[-1])
        except (ValueError, IndexError):
            return f"benchmark produced no measurement: {result.stdout.strip()[:200]!r}"
        if "error" in payload:
            return payload["error"]
        return payload["best_ns"], payload["stdev_ns"]

    def compare(
        self,
        original: str,
        patched: str,
        benchmark: Benchmark,
        logical_name: str = "target.py",
    ) -> PerfMeasurement:
        """Measure both sides and classify the difference."""
        before = self.time_once(original, benchmark, logical_name)
        if isinstance(before, str):
            return unmeasurable(benchmark.label, before)
        after = self.time_once(patched, benchmark, logical_name)
        if isinstance(after, str):
            return unmeasurable(benchmark.label, after)
        return classify(benchmark, before, after)


def classify(
    benchmark: Benchmark, before: tuple[int, int], after: tuple[int, int]
) -> PerfMeasurement:
    before_ns, before_sd = before
    after_ns, after_sd = after
    # Combine the two runs' spreads: the question is whether the *difference* is larger than
    # the noise in the difference, not larger than the noise in either half.
    pooled_sd = int(statistics.hypot(before_sd, after_sd))
    delta = abs(after_ns - before_ns)

    too_few = benchmark.repeats < MIN_REPEATS
    too_noisy = before_sd > MAX_NOISE_RATIO * before_ns or after_sd > MAX_NOISE_RATIO * after_ns
    if too_few or too_noisy:
        # Reported before the delta is even considered. A big difference measured badly is
        # still measured badly.
        verdict = "inconclusive"
    elif delta < max(NOISE_SIGMAS * pooled_sd, MIN_RELATIVE_DELTA * before_ns):
        verdict = "inconclusive"
    else:
        verdict = "slower" if after_ns > before_ns else "faster"
    return PerfMeasurement(
        label=benchmark.label,
        before_ns=before_ns,
        after_ns=after_ns,
        repeats=benchmark.repeats,
        stdev_ns=pooled_sd,
        verdict=verdict,
    )
